### ISSUE TITLE
Slots compatibility

### ISSUE THREAD

**Issue by Mauler78** [shudnal/ExtraSlots#5] opened 2024-11-14 17:53 UTC
I am using Jewelcraft which has a number of new slots.  I was hoping that the utility slots would be able to handle it, but dones't seem to work.  The biggest thing I have been able to test is when you make a tome and add it to your tome slot you get a certain amount of etir (mana), and in your mod it does not matter where I put the tome, I get nothing

Not sure if there is a way for you to add or adjust your mod to have these as configurable slots, I love the mod just doesn't quite work 100%.  Also any reason that the food does not have a key to press so you can eat on the fly?

**Comment by shudnal** [comment] 2024-11-15 01:59
I've checked Jewelcrafting code and it seems there are no compatibility issues. But the reason your extra utility slots could not work is because of Jewelcrafting "2 - Socket System" -> "Maximum number of Sockets" config value. I have no idea how to set it properly but you can try to increase it and see.

After I set "Maximum number of Sockets" to 10 and equipped 3 rings with 3 sockets each and necklace it seems that every socket is working.

![image](https://github.com/user-attachments/assets/f2a7910f-bc9e-498c-9ec4-b15b1730134c)


I have plans on adding Jewelcrafting custom slots but later after initial issues will be fixed.

You can't use food more often than once per 10-15 minute.  In general you don't need to use food in combat or reactively. And adding more hotbars with food will clutter UI even more. So no food hotbar is deliberate choice but if you have strong arguments it's discussable.

**Closed by shudnal** 2024-11-15 01:59 UTC

**Comment by Mauler78** [comment] 2024-11-15 03:30
Did you try equipping a book or tome?  I the current inventory mod I am
using there is a specific spot it goes and it give  you etir (or whatever
they are calling mana).  I did not seem to be able to get that to work with
your mod. I did not test rings or other things of that sort since I don't
currently have any.

Also, I do hear you about the food, and I use a mod that extends the
duration of food as well, so yes it not likely that I would need them on a
hot key, and honestly have them out of the backpack is kind of nice

**Comment by shudnal** [comment] 2024-11-15 03:51
I am not familiar with Jewelcrafting at all. I don't know what is tome or book.

**Comment by Mauler78** [comment] 2024-11-15 03:54
OK, well I thought it was just the book and it seem like it is all the
utility spaces are not registering items put there.  Clearly as they are
working for you  there could be a conflict with other mods possibly

I have attached a couple screenshots.

**Comment by shudnal** [comment] 2024-11-15 03:57
I installed JC and don't see any book or tome there. Only rings and necks.
I can't see screenshots.

**Comment by Mauler78** [comment] 2024-11-15 03:58
![vh azu space mod](https://github.com/user-attachments/assets/952654c6-0e8f-4c3e-aa70-8d951c714cd5)
![vh extra space mod](https://github.com/user-attachments/assets/05016159-7e95-4957-9ea7-11c69d38350f)

**Comment by shudnal** [comment] 2024-11-15 04:06
There is another mod. Not Jewelcrafting. There is nothing called tome or something like that in JC.

**Comment by shudnal** [comment] 2024-11-15 04:11
I guess this is the MagicPlugin
![image](https://github.com/user-attachments/assets/2ee93a9a-29b9-4a87-bd7c-623d120a6b7d)

**Comment by Mauler78** [comment] 2024-11-15 04:24
Ahh, you are correct.

If it matters I am also running the Therzie suite of mods, Warfare, Armory, Wizardry, and Monstrum.

Is the MagicPlugin causing the issue?

**Comment by shudnal** [comment] 2024-11-15 05:31
That's not the issue but not yet implemented compatibility. I'll make it work eventually,

**Comment by shudnal** [comment] 2024-11-15 05:56
I've checked MagicPlugin and MagicRevamp. Both mods work as intended. I've tested with book and tome and eitr adds accordingly.
![image](https://github.com/user-attachments/assets/3716df3e-8675-4413-8d64-4c747efc3c11)

**Comment by Mauler78** [comment] 2024-11-15 11:52
idk then, for me it isn't working.

Does the load order of the mods matter?

**Comment by shudnal** [comment] 2024-11-15 15:23
I guess there is some other mod then.

**Comment by Mauler78** [comment] 2024-11-15 19:06
I have disabled a number of mods that mess with bags and inventory, but not
since the last update you provided I can not equip armor or utility items.
Food, arrows and quick bar seem to be fine.

I tried disabling all the mods except the most critical ones and still had
the same issue, so I don't know if there is some remnant of an old mod that
is messing with yours or what the deal is.

**Comment by shudnal** [comment] 2024-11-15 19:58
Your current mod list would be helpful

**Comment by shudnal** [comment] 2024-11-15 23:59
SmarterContainers looks suspicious. I'll check later.

**Comment by shudnal** [comment] 2024-11-16 10:15
I have made the fix for utility equipment in 1.0.5. Pls check if it works.

I've also tested SmarterContainers and some other mods and it works well. There are couple of mods still waiting to be tested.

You should remove RequipMe because it could mess with tombstone interaction and this mod already has similar configurable feature. Auto equip of weapon and shield I will add in next version where RequipMe will be marked as incompatible.

**Comment by Mauler78** [comment] 2024-11-16 21:10
ok, so I am running you latest version, and it all seems to be working.
Items are being recognize for the values for example the belt is giving the
carry bonus, books are giving me etir.

The only "issue" and this might actually be a feature you intended, is that
I can not drag and drop equipment into my paper doll, example to equip
armor, I must right click it from my inventory and then wait for it to
equip, and to remove I must right click on the paper doll and wait for the
white box to go away then I can drag it to my backpack.  This might be as
designed, but it took me a minute to figure it out.

**Comment by shudnal** [comment] 2024-11-16 21:47
This is by design you're right. Fast equip/unequip is what I strongly dislike in AzuEPI. And strict limit of item must be equipped to be in slot at EaQS is also too restrictive. So this mod is a middleground. You can place item in equipment slot without equipping it. But you must equip/unequip it by hand and wait while performing equip action.

If you press equip on other item after equipping it will swap with current item in slot btw.

**Comment by shudnal** [comment] 2024-11-17 02:17
I finally get what you meant in second part when items could not be dragged into slot. Fixed in 1.0.7. Now you can drag item in slot like it was in previous version.

**Comment by Mauler78** [comment] 2024-11-17 03:29
Awesome, I will update and check it out...just and fyi Thunderstore mod
manager is only recognizing 1.0.6.

Also, I would like to thank you for being so responsive and working with me
to improve your mod and make it more mod friendly and usable.

**Comment by shudnal** [comment] 2024-11-17 12:36
Well more work now means less work in the future. I'm also interested to make mod that doesn't break or lag or cause compatibility issues.
